### ISSUE TITLE
apollo client:codegen change files extension + add eslint-ignore

### ISSUE THREAD

**Issue by adrienharnay** [apollographql/apollo-tooling#1004]
Hey,

Currently, when generating typescript typings, files are written next to the gql queries and named `[fileName].ts`. It could be neat if we could provide a custom extension (say `.d.ts`).

Also, it would be great to add `/* eslint-disable */` at the top, just like the line that disables tslint.

Thanks in advance!

**Comment by klemenoslaj** [comment]
I just wanted to open very similar issue.

In my opinion `.d.ts` should even be used by default, because definition files do not intervene with the typescript configuration, thus eliminate any potential problems down the road with other tools in the build chain.

Having possibility to change the extension is of course the step into the right direction.

**Comment by adrienharnay** [comment]
I agree with you 👍 Do you want me to file a PR?

**Comment by klemenoslaj** [comment]
Sure, I think that would be a nice addition :+1: 
Would love to hear the opinion of some repo member as well.

**Comment by adrienharnay** [comment]
Yup, will wait for validation before filing the PR. I think I know which files I need to change to make this happen

**Comment by slorber** [comment]
Hi,

Just wanted to point out I'd also appreciate to be able to generate .d.ts because it's more explicit for other toolins that it's just a TS definition file.


For example I'm building an Apollo example using Gatsby and Gatsby try to use the .ts files generated as static pages:

> error [/Users/sebastienlorber/Desktop/projects/gatsby-plugin-react-native-web/examples/todos/src/pages/__generated__/GET_TODOS.ts] The page component must export a React component for it to be valid

But it automatically excludes .d.ts

Currently my only workaround to get Gatsby ignore those generated files is to move them outside of /pages folder or to use a shitty /__tests__ folder name for generated defs instead of __generated__ :/

**Comment by adrienharnay** [comment]
Hey @JakeDawkins, could we have your opinion on this please?

**Comment by JakeDawkins** [comment]
@adrienharnay @slorber this sounds very reasonable to me! I imagine the new extension wouldn't be the default for now, since it's technically a breaking change. It could maybe be the default in a 3.0 roadmap though.

I'm not sure about the eslint comment. Are you using eslint with ts typedef files?

@trevor-scheer what do you think about this?

**Comment by adrienharnay** [comment]
Hey, actually the eslint comment has been released already 🙂 And for the record, @typescript-eslint is gaining popularity after [tslint announced they will join efforts with eslint in 2019](https://medium.com/palantir/tslint-in-2019-1a144c2317a9).

For the file extension, I can file a PR that adds a new config/CLI option `fileExtension` if that sounds reasonable to you!

**Comment by JakeDawkins** [comment]
That sounds good to me!

I don't love the idea of an additional flag just for this one use case, but I'm not sure there's an alternative. I think it'd definitely just be a CLI flag, not an option in the config file though.

**Comment by adrienharnay** [comment]
Noted, I will go with the CLI flag. Thanks for your advice!

**Comment by adrienharnay** [comment]
Opened #1130, I would need some guidance with it but it shouldn't be far from done 🙂

**Comment by trevor-scheer** [comment]
The flag sounds good to me, and the request is reasonable. Default `.d.ts` sounds like a good move for our next major release. Taking a look at the PR now. Thanks @adrienharnay!

**Comment by mmeeshari** [comment]
Uu

**Comment by mnpenner** [comment]
I'm not a TypeScript expert, but I think we need to drop the `export` keyword before the `interface`s when using `.d.ts`, that way they can be scooped up by `tsconfig.json` when using:

```json
    "include": [
        "src/**/*.d.ts"
    ]
```
