### ISSUE TITLE
apollo-codegen introspect-schema handle multiple endpoints

### ISSUE THREAD

**Issue by wamra** [apollographql/apollo-tooling#1063]
Hi, 
I need help with the following command. 

> apollo-codegen introspect-schema

We have multiple endpoints of graphql; e.g., **http://host:port/service1, http://host:port/service2, http://host:port/service3**

I am wondering if there is a way to introspect all of these services into a single **combined-schema.json** file so that I can use that single file to generate types for different queries with the same command line

> apollo-codegen generate src/**/*.graphql --schema src/dal/generated/combined-schema.json --target typescript --output src/generated/apollo-generated-models.tsx --addTypename

These services utilize the same types behind the scenes, and the aim is to simplify and generate a single consolidated *.tsx file instead of different multiple ones. 

Thoughts ?

**Comment by JakeDawkins** [comment]
Hi @wamra! I don't believe that's supported. 

Newer versions of the CLI may offer a workaround though. If you have multiple schema files (in a graphql/js file) and they fall under the `includes` glob and get picked up, any types generated will be based off the full combined schema. Not just a single one. The only gotcha is having overlapping types (like Query/Mutation). That wouldn't work. So it'd be a bit more manual work, but may be worth it. Check out #841 for more info on this.

I'll close this issue, since adding features to an older version of the CLI isn't something we can easily do.
