### ISSUE TITLE
Extraction strips quoted operation parameters

### ISSUE THREAD

**Issue by ellioseven** [apollographql/apollo-tooling#1099]
**Intended outcome:**

Operation parameter values remain in the parsed operation string.

```
fragment Articles on Query {
  article: getArticles(
    sort: [{ field: "created", direction: ASC }],
  ){
    count
    entities {
      ...Article
    }
  }
}
```
Parses to:

```
fragment Articles on Query { article: getArticles(sort: [{ field: "created", direction: ASC }],){ count entities { ...Article } } }
```

**Note:** `sort.field` === `"created"`

**Actual outcome:**

Operation parameters values are stripped from the operation string.

```
fragment Articles on Query { article: getArticles(sort: [{ field: \"\", direction: ASC }],){ count entities { ...Article } } }
```

**Note:** `sort.field` === `""`

**How to reproduce the issue:**

Run `client:extract` on a fragment such as:

```
fragment Articles on Query {
  article: getArticles(
    sort: [{ field: "created", direction: ASC }],
  ){
    count
    entities {
      entityId
    }
  }
}
```

**Versions**

`2.6.0`

**Comment by ellioseven** [comment]
I have a live example here: https://codesandbox.io/s/lpoq08knnm

**Comment by ellioseven** [comment]
I can see this issue stems from: https://github.com/apollographql/apollo-tooling/blob/master/packages/apollo/src/commands/client/push.ts#L29

I think that there should be a `hideCertainLiterals` opt out arg, there are uses cases when string literals are highly desirable, especially as default variables. Having these wiped out causes queries to simply not work and error out.

**Comment by adampilks** [comment]
Facing this same issue.  My use case is that I want to extract all queries from the codebase and based off of some mocking config, auto generate mock data for all queries.

We have some that have fixed variables and these are always stripped out during the extraction.

**Comment by damondoucet** [comment]
Also running into this issue. Our use-case:

1. We're using `apollo client:extract` to generate a query whitelist - at build time, we extract all queries in the app, merge them with historical queries, and only serve those in our backend.
2. `apollo client:extract` strips out literals, including parameters to directives. The comment below indicates the team is considering removing that, though it was added a while back and I haven't seen any movement (this issue is also rather old).

https://github.com/apollographql/apollo-tooling/blob/master/packages/apollo-graphql/src/operationId.ts#L77

Essentially this means that the server and client will disagree on the intended query, which is really problematic for us. I haven't found a way to configure this in `apollo client:extract`, and the best solution I've come up with so far is to write our own tooling to extract the queries without stripping away literals.

I understand changing it on your end would probably be a breaking change and take a fair amount of effort, so any guidance in the meantime would be greatly appreciated!

**Comment by damondoucet** [comment]
(@jhampton pinging you AD in our email thread - I found this older issue and bumped it rather than creating a new one)
