### ISSUE TITLE
No types/dist folder for apollo-server-plugin-operation-registry

### ISSUE THREAD

**Issue by jhalborg** [apollographql/apollo-tooling#1194]
**Intended outcome:**
Trying to use the `apollo-server-plugin-operation-registry` plugin, expecting it to work in my standard TS project. 

**Actual outcome:**
When looking in `node_modules` after installation, the installed package contains the source code in `.ts` files, but no `dist` folder or own `node_modules` - hence, no auto-complete when trying to use the plugin in my Apollo Server instantiation, and a 

```
Error: Cannot find module 'apollo-server-plugin-operation-registry'
```

error when trying to run the code, seeing as the code isn't compiled, but it's `package.json` points to `dist/index.js` as the entry point (and `dist/index.d.ts` as types)

![registry](https://user-images.githubusercontent.com/6643672/56207980-59196f00-6050-11e9-8449-1745beb4bd20.png)

**How to reproduce the issue:**

Follow the [quickstart for registry](https://www.apollographql.com/docs/platform/operation-registry) with the version 

`"apollo-server-plugin-operation-registry": "^0.1.0-alpha.2",`

**Workaround**
Use v `0.1.0-alpha.2` instead for now. Not sure what the difference between the two is, can't find docs or changelog

**Comment by abernix** [comment]
Please try again with `apollo-server-plugin-operation-registry@0.1.0-alpha.3`, which was just published.  It appears that the `-alpha.2` was published without emitting any output during the build because a weird build circumstance that occurred because of the new `tsconfig.tsbuildinfo` cache files in TypeScript 3.4.

Thanks for pointing this out!
