### ISSUE TITLE
Support *.gql, *.graphql files with `client:codegen`

### ISSUE THREAD

**Issue by ericbiewener** [apollographql/apollo-tooling#1372]
It looks like `client:codegen` currently only supports tagged template literal parsing. I'd like it to also support `*.gql` and `*.graphql` files.

**Comment by JakeDawkins** [comment]
This is already supported. It sounds like you may be running into a config issue where the CLI isn't picking up those files, because it doesn't know where to look.

The default place that tooling looks to find these files follows this glob pattern: `src/**/*.{ts,tsx,js,jsx,graphql,gql}`

More info on the `includes` config can be found [here](https://www.apollographql.com/docs/references/apollo-config/#clientincludes). 

If you have questions about how to configure projects, the [spectrum community](https://spectrum.chat/apollo) is a great place to ask questions. If you believe there is an actual bug with tooling, let me know and I can potentially reopen this.
