### ISSUE TITLE
Configuring client/sever project - apollo.config.js

### ISSUE THREAD

**Issue by nanandn** [apollographql/apollo-tooling#1514]
The documentation (https://www.apollographql.com/docs/references/apollo-config/) says 

> The apollo.config.js file is meant to describe configuration for a single project only. If used in a monorepo with multiple projects, there should be a separate config file for each project.

In my node JS application I have both the client and server side code in the same project in different directories. This is not a lerna monorepo.

app
    - src
           - server
           - client

In this case, what should the apollo.config.js look like.
- Can I have one apollo.config.js with both client and service configurations?
- If I need two files, where should they be?

Thanks
Anand

**Comment by breathe** [comment]
I have similar question to OP -- also wondering if I _have_ to have the .env file placed in both directories -- would prefer to have a single .env file in a directory parent to both the client and server ...

**Comment by JakeDawkins** [comment]
@nanandn Sorry for the late response here, I hope you got it figured out! 

I'm not sure what your `src` folder looks like, but if all your client operations/schema live in the `client` folder and all your service's schema lives inside the `server` folder, you'd need two `apollo.config.js` files, one in `client` and one in `server`. 

As for `.env` files, unfortunately, right now you'd need one in both directories as well. I know that's annoying, and both issues are something we're actively working on designing a solution for at the moment.

You can see examples for both of these things in the [fullstack tutorial code](https://github.com/apollographql/fullstack-tutorial/tree/master/final). 

I'll close this, but I'm happy to reopen if there are any bugs to discuss :)

**Comment by tvvignesh** [comment]
@JakeDawkins Hi. Just wanted to get an idea on the status of this now. I use Dgraph (https://dgraph.io/) for my database. So, my database exposes GQL endpoint and I do some operations on the server and I expose a GQL endpoint from my server as well which my client consumes (again through GQL). So, for me its GQL all the way and the structure of one of the components in the server looks somewhat like this:

<img width="210" alt="Capture" src="https://user-images.githubusercontent.com/1165845/94253333-c9653900-ff42-11ea-8758-3e93862454b0.png">

As you can see, I store the mutations and queries which I have to do on the db in the db folder and the schema of the server in the schema folder (so, its essentially the same layer acting as both GQL client and the server).

May I know how do I handle such cases using `apollo.config.js` ? Since every component has its own set of db queries and mutations, it won't make sense for me to move that separately.

Also, it won't make sense to move the schema out of the component as well since each component has its own schema (which I later combine with schema stitching and federation). 

Any help appreciated. Thanks.
