### ISSUE TITLE
Repo for graphql-language-service-interface

### ISSUE THREAD

**Issue by OliverCole** [apollographql/apollo-tooling#1553]
Hi - where is the repo for [@apollographql/graphql-language-service-interface](https://www.npmjs.com/package/@apollographql/graphql-language-service-interface)? The [repo linked](https://github.com/apollographql/graphql-language-service#readme) from NPM is 404.

This package, along with `parser`, `types` and `utils` are published on NPM without a license, which means I can't use them.

Could this be resolved?

**Comment by abernix** [comment]
The packages you're referring to were once forked from an upstream repository located at https://github.com/graphql/graphql-language-service/.

Today, as noted on on that project's README, that repository has been rolled into the GraphiQL IDE monorepo project and now lives in https://github.com/graphql/graphiql/tree/master/packages/, where newer versions of it are licensed under the MIT license.

Apollo created the fork (and published them to npm within our own `@apollographql/` namespace) to remove a dependency on `graphql-config` and `graphql-import` which were problematic since they brought in hard-coded versions of `graphql`, which caused problems for our tooling offerings, like the Apollo VSCode extension.

When Apollo originally forked those packages to apply the aforementioned changes, those packages were under the terms of the Facebook license (This all happened prior to Facebook broadly [relicensing GraphQL-related over to the MIT license](https://engineering.fb.com/core-data/relicensing-the-graphql-specification/)).

We no longer maintain the fork of the package, but the branch point would have been [this commit](https://github.com/graphql/graphql-language-service/tree/a80c0a5035c0bbd57e5c1fd7e2b64d65013a6f66) in the [upstream repository](https://github.com/graphql/graphql-language-service/). You can view the license terms at that point in history via [this license file](https://github.com/graphql/graphql-language-service/blob/a80c0a5035c0bbd57e5c1fd7e2b64d65013a6f66/LICENSE).  And again, our only changes to it were the removal of the aforementioned dependencies and the associated code (which was not important to our functionality).

**Comment by OliverCole** [comment]
Appreciate the response - to clarify, you're saying that `apollo@2.21.2` depends on forks of those libraries which are no longer maintained? So this issue can't/won't be fixed?

The issue from my end is an automated analysis of the licensing, which depends on either the `LICENSE` file in the git repo linked from `package.json`, or the license field as published on the NPM registry. The `apollo@2.21.2` package is fine, but when it spiders the dependencies, these packages fail to find either - and so I can't use the entire stack, which is unfortunate.

**Comment by edmundas-ramanauskas** [comment]
we have exactly the same problem, these packages were reported:
- @apollographql/graphql-language-service-utils - https://www.npmjs.com/package/@apollographql/graphql-language-service-interface
- @apollographql/graphql-language-service-parser - https://www.npmjs.com/package/@apollographql/graphql-language-service-parser
- @apollographql/graphql-language-service-types - https://www.npmjs.com/package/@apollographql/graphql-language-service-types
- @apollographql/graphql-language-service-utils - https://www.npmjs.com/package/@apollographql/graphql-language-service-utils

wouldn't it be possible for you to update to packages from https://github.com/graphql/graphiql/tree/master/packages/ ?

**Comment by smoak** [comment]
I agree. I think this should be re-opened. Newer versions of apollo (e.g. 2.28.3) still depend on these forked packages (with the facebook license). This means `apollo` et all is unusable.
