### ISSUE TITLE
Generate queries (& mutations) from code, or automatically from resolvers

### ISSUE THREAD

**Issue by vjsingh** [apollographql/apollo-tooling#1664]
I find myself often wishing for a better solution for two of the following related issues:

- Writing graphql queries and mutations in `gql` template strings is not ideal. It would be better to be able to write all of our queries and mutations in code and not in a string. There is tooling to support the strings, but code would still be better.
- Whenever I create a new resolver on the server side, I have to update the corresponding query/mutation on the client side. More importantly, updating these can be cumbersome or introduce bugs.

It seems that there are two possible solutions here:

1. Create a way to generate queries/mutations from code. Something like the https://github.com/prisma-labs/nexus-prisma project. Queries/Mutations would be written as objects in the language, and gql template strings would be generated by the code itself. This seems more semantic and developer-friendly.
2. For the default case, add the ability to automatically generate queries/mutations based on my resolvers.

Here's an example of my workflow and why it's repetitive. I tried searching quite a bit, but perhaps I'm missing something?

**Using Prisma (nexus-prisma plugin) and Apollo Client**

1. Add new resolver to the server
```
server/resolvers/Mutation.ts

    t.string('addFriend', {
      args: {
        targetFriendId: stringArg({required: true}),
      },
      resolve: async (parent, args, ctx) => {
        ...<Change the database>
      },
    });

```

2. Create new mutation on client side
```
client/util/ApolloUtil.tsx

export const ADD_FRIEND = gql`
  mutation AddFriend($targetFriendId: String!) {
    AddFriend(targetFriendId: $targetFriendId)
  }
`;

```

Is this the recommended workflow? Surely people can't love working inside the graphql language, with it's `$`s and repetitive arguments.

**Comment by JakeDawkins** [comment]
Hey @vjsingh! Thanks for asking!

Your usage of `queries` and `mutations` here is a _bit_ confusing, since `query` could refer to a resolver, a type definition, the client-side operation string, or the actual executed operation from the client at runtime. But I think I understand your ask.

Some people and organizations do prefer to define types and resolvers all in "code" like you showed, but we've found great benefit to using SDL (the graphql schema definition language) to define schemas. Its readability and navigability are extremely important, and the language is easy to parse through, create an AST from multiple files, and do static analysis on it.

Of course, this does mean that you still have to manually update resolvers, but imho, that's not that big of a deal or a maintenance burden. Especially not large enough of one to rewrite all of our tooling to support a new way of defining schemas.

As for generating mutation/query strings for client-side usage, we don't have plans or intend on writing a tool to support that in the near future. There's definitely some use-case for it (obviously), but we don't think the use-case is large enough to dedicate time to building and maintaining tooling around it. Many (if not most) of the use we see is building out larger operations with more complex return types and subselections that really can't be generated. So generating unused operations (or unhelpful ones) for every root type just don't seem that beneficial.

I hope this all makes sense, and doesn't sound dismissive. There's definitely a use-case for what you're talking about. We just haven't found it necessary or useful _enough_ to dedicate serious time to supporting it :)

**Comment by vjsingh** [comment]
@JakeDawkins 

Thanks so much for the detailed response! That answers all my questions. I think overall my use case, although in production, is still very small, and it makes sense that you are mostly working on supporting larger enterprise use cases. It's true the maintenance burden is not huge, but it is something that's come up again and again for me over the past 6 months of building out my application, so I thought I'd see what your guys' thoughts are.

And yes you're right about the confusing usage of `query` and `mutation`. Glad you understood my ask anyway. Cheers!
