### ISSUE TITLE
Due to the Chinese network environment, blocked by the firewall, the execution of the npm run codegen command failed

### ISSUE THREAD

**Issue by sinianzhiren** [apollographql/apollo-tooling#1793]
I have set up a network ladder and set up a proxy for the terminal, but it still does n’t work. Excuse me, are there any other options?
<img width="831" alt="屏幕快照 2020-02-07 上午9 53 12" src="https://user-images.githubusercontent.com/26428090/73994298-066ac400-4990-11ea-976a-d7dff80d9193.png">

**Comment by glasser** [comment]
Hi, I believe I've fixed this issue. Since I don't work in a corporate proxy environment myself, I'd appreciate help testing the alpha from folks who've faced this issue.  You can install the alpha with `npm i apollo@2.32.0-alpha.0`.  This uses the `global-agent` npm package with the standard env vars `HTTPS_PROXY` and `NO_PROXY` (no `GLOBAL_AGENT_` prefix needed). Will publish this as non-alpha once I get confirmation it works for folks!

**Comment by glasser** [comment]
Fixed (hopefully!) in `apollo@0.32.0`.
