### ISSUE TITLE
Fallback to Apollo registry

### ISSUE THREAD

**Issue by tvvignesh** [apollographql/apollo-tooling#1848]
Hi. I am using Apollo Registry for pushing and retrieving all my schema which used to work properly and has been great. But, I got thinking after some issues which cropped up recently (http://status.apollographql.com/) in the service, how do I handle such failures if and when it happens in the future without causing any disruption to the development process.

I am not operating at a huge scale now nor will I for quite some time, but if I do in the future, how will I handle such failures since all my CI/CD processes relating to graph depend on the registry for pushing/pulling the schema to/from the registry and if the registry fails, I can't pretty much do anything.

While this is how things are when any service provider you are relying on fails, I just wanted to make sure that there is some fallback mechanism in place during such downtimes or issues. Any thoughts on how we can achieve this?

Posting it in this repo since I was wondering if there is some plan to have some tooling in place to cater to such scenarios. Thanks.

**Comment by zionts** [comment]
Hi there 👋 and thanks for reaching out about this! I can certainly appreciate wanting to make sure you're protected from any downtime we might experience. I want to start by apologizing for our recent downtime and how it has made it more challenging to achieve your workflows. It's something we don't take lightly on the team and we've been hard at work digging into the root cause of the incidents that you alluded to, and we were able to merge what we _hope_ to be a fix into `master` today and we plan to push out the mitigation to production in a few short hours.

That being said, I think you're absolutely right to want to understand how you're affected if the Apollo registry is unavailable, particularly for supporting your federated GraphQL deployment. Assuming that you're using managed federation, interrupts to Apollo's cloud offering will not have an effect on the ability of your gateway to fetch its remote configuration. This is because the configuration files are actually hosted through an external CDN (Google's to be precise). However, if Apollo Graph Manager is experiencing downtime, then you will be unable to push out new changes to your configuration or reliably run validation `service:push`. There's a bit more information on reliability and security in [the docs](https://www.apollographql.com/docs/graph-manager/federation/#reliability-and-security) as well that can speak to this.

We take our responsibility of maintaining uptime very seriously, and I hope you will accept my apologies for the challenges it caused you. I'm happy to answer any specific questions you might have around how to best protect yourself from any disruptions to our service's availability.

**Comment by zionts** [comment]
Likewise, as to ideas around tooling in the repo for mitigation, we are certainly open and eager to hear ideas you might have! Do you have any specific workflows in mind?

**Comment by tvvignesh** [comment]
@zionts Ahh. Interesting. Really respect the work you guys are doing behind the scenes. Love the way apollo has made things damn easy for me to work with GraphQL. I thought even the gateway may be affected at some point but this makes a lot of sense hosting it in a CDN outside.

Regarding maintaining the uptime of the registry to make sure CI/CD does not fail, maybe the CLI can be made offline first in the future - sync with the registry whenever it is available, and when you do service:push, it can get saved locally - sync immediately if the remote registry is available, if not, save it and wait till the registry comes back up and then sync it.

Don't want to make things complicated, but just in case this becomes a big issue in the future, maybe you can look at this approach.

Thanks again.

Similar to the way how offline mobile apps work. The only important thing I see in this approach is that the CI process has to wait till the sync is complete with the registry before it proceeds.

The CLI can keep retrying again and again at periodic intervals till the remote registry becomes available.

**Comment by zionts** [comment]
Happy to help @tvvignesh — thinking about offline options and on-prem options are certainly something on our mind for the long-term roadmap :)
