### ISSUE TITLE
Docs still reference env variable 

### ISSUE THREAD

**Issue by brianebill** [apollographql/apollo-tooling#1890]
Not sure if this is the correct repo, but thought I'd start here:

**Intended outcome:**
Enter the correct env variable

**Actual outcome:**
Docs reference `ENGINE_API_KEY` while this [PR](https://engine.apollographql.com/org/gh.brianebill/graphs?overlay=publish-your-schema&serviceId=thisis-great) seems to have changed the name to APOLLO_KEY

**How to reproduce the issue:**

Create a [new graph](https://engine.apollographql.com) and verify the docs are incorrect

**Versions**
Public website

**Comment by JakeDawkins** [comment]
Hey @brianebill, thanks for opening this! Yeah, there wasn't a clean way to roll over the api key to the new name without causing some mismatch, since `apollo-server` is still awaiting the update to the new key name 😞 

A short-term solution we're gonna go with is allowing _both_ `ENGINE_API_KEY` and `APOLLO_KEY` to work simultaneously, preferring the newer `APOLLO_KEY` and wait for apollo-server to update to fully move over all the docs. I'm not 100% sure if we'll keep the _deprecation_ warning though. Because it technically _is_ deprecated. Still thinking about that.

**Comment by brianebill** [comment]
Sounds good. Just for reference, if anyone stumbles on this post, I wasn't able to make the connection with `ENGINE_API_KEY`.
