### ISSUE TITLE
`json-modern` enhancement requests

### ISSUE THREAD

**Issue by designatednerd** [apollographql/apollo-tooling#1909]
Related to changes added to implement #1814, the `json-modern` has a few minor bugs and pain points not related to the actual generation of type information I'd like to see addressed: 

- [ ] `outputFileURL` being passed as an option no longer causes `operationID` to get generated. 
- [ ] Probably related since it's what's used to generate `operationID`, the `sourceWithFragments` property present in previous JSON integrations is no longer there. This provided the source with full content of the fragments appended. 
- [ ] It looks like `mergeInFieldsFromFragmentSpreads` is not being respected - output is identical if I pass `true` or `false` for this.
- [ ] The `selectionSet`'s `selection`s  are using a lot of overlapping properties - if something's a field it has a bunch of properties, if it's a Fragment Spread it has other properties, if it's a conditional it has even different properties. In previous versions these were totally different types. How horrendous would it be to go back to using different types, or is this something I should try to do on the parsing side instead

**Comment by JakeDawkins** [comment]
Yep! Thismakes sense. It looks like at least the first 3 of these issues are due to using the newer IR generator and not doing the transforms from the legacy generation. I'm going to switch back the legacy generator with the `typeNodes` field added (which I probably shoudl've just done in the first place 🤦) and see how much of this is just fixed automatically (I think and hope all)

**Comment by designatednerd** [comment]
(confirmed resolved)
