### ISSUE TITLE
Support GLOBAL_AGENT_HTTP_PROXY for apollo CLI

### ISSUE THREAD

**Issue by john-dodson** [apollographql/apollo-tooling#1967]
The apollo module should be updated to support GLOBAL_AGENT_HTTP_PROXY like apollo-server. Because it doesn't I currently have to whitelist an egress to engine-graphql.apollographql.com from a secure cluster in order to upload my schema to graph manager during CI.

**Comment by antonmo46** [comment]
same issue maybe instead of node-fetch to use this one:
https://www.npmjs.com/package/node-fetch-with-proxy

**Comment by glasser** [comment]
Hi, I believe I've fixed this issue. Since I don't work in a corporate proxy environment myself, I'd appreciate help testing the alpha from folks who've faced this issue.  You can install the alpha with `npm i apollo@2.32.0-alpha.0`.  This uses the `global-agent` npm package with the standard env vars `HTTPS_PROXY` and `NO_PROXY` (no `GLOBAL_AGENT_` prefix needed). Will publish this as non-alpha once I get confirmation it works for folks!

**Comment by glasser** [comment]
Fixed (hopefully!) in `apollo@0.32.0`.
