### ISSUE TITLE
Apollo-codegen outputs empty file

### ISSUE THREAD

**Issue by seklyza** [apollographql/apollo-tooling#444]
- [x] good first issue

Whenever I run `apollo-codegen` on my terminal (`yarn apollo-codegen generate src/**/*.tsx --schema schema.json --target typescript`), the output file is filled and I can use the types.
However, I tried automating the process of generating types, so I added a NPM script to generate the types. The `schema.json` file is correctly generated, but yet the output typescript file is empty. So I created a file called `generateTypes.sh` which includes:

```sh
yarn apollo-codegen introspect-schema ../server/src/schema.graphql --output schema.json
yarn apollo-codegen generate src/**/*.tsx --schema schema.json --target typescript
```

When I ran the file, the output file is still empty. (It was created, but was empty)

Am I missing something? Am I not using `apollo-codegen` correctly or it is a bug?

**Comment by shadaj** [comment]
The first parameter to `generate` is the path to the `graphql` queries you want to generate types for, so something like `src/**/*.graphql`. Then you'll need to specify the output with the `--output` setting (this can be either a file or directory).

**Comment by seklyza** [comment]
@shadaj Yeah, but when I am running the command normally it works, and when I am running it using Yarn/NPM scripts it doesn't

**Comment by shadaj** [comment]
@seklyza I see what you mean. What version of Apollo Codegen do you have installed globally and locally?

**Comment by craigrmccown** [comment]
I am running into the same issue using version 0.20.1, and I am also using Yarn workspaces in a monorepo. The command I am using works when run directly, but it produces an empty file when run via Yarn. To help track down the issue, I've tested these scenarios:

- Run from the root directory of the monorepo with apollo-codegen installed in the top-level node_modules
- Run from the workspace directory with apollo-codegen installed in the top-level node_modules
- Run from the root directory of the monorepo with apollo-codegen installed in the workspace directory via `nohoist`
- Run from the workspace directory with apollo-codegen installed in the workspace directory via `nohoist`

All of these resulted in an empty file. Also, if it helps, I am using `--target flow`, so the issue isn't related to the output target. My findings seem to indicate that this issue is not related to Yarn workspaces, but I do find it curious that @seklyza is experiencing the same issue and also using workspaces.

I would be interested to find out if this same thing happens in a project that doesn't use Yarn workspaces so we can rule that out as the source of the issue. I don't have time to set up a dummy project to test this right now, so I would appreciate it if someone else can find the time!

**Comment by neilrjones** [comment]
I was having the same issue. However in my case vscode editor was reformatting my gql tags from gql` to gql `. In other words, vscode was adding a space between gql and the ` (back tick).  I am guessing apollo is only searching for gql` .  Hope this helps!
