### ISSUE TITLE
support imports(graphql-import) in .graphql files

### ISSUE THREAD

**Issue by chandu0101** [apollographql/apollo-tooling#495]
enums.graphql

```gql
enum Role {
 ADMIN
 USER
}

```

server.graphql

```gql
# import Role from "enums.graphql"
...
```
`apollo codegen:generate --schema ./schema/server.graphql..`
Error : `Error: Unable to read file ./schema/server.graphql. Type "Role" not found in document.`

**Comment by chrisdrackett** [comment]
I see this is closed but I'm still having issues with the same thing. I'm trying to import in my main `schema.graphql` stuff generated by Prisma in a `prisma.graphql` file. This does not work and as far as I can tell it is because the import isn't working with codegen? Maybe I'm missing something else?
