### ISSUE TITLE
Support dotenv

### ISSUE THREAD

**Issue by jhalborg** [apollographql/apollo-tooling#594]
- [x] feature
- [x] docs
- [x] good first issue

It would be super cool if one could

```npx apollo schema:publish -e .env.stage```

for example, and have a `.env.stage` file a la

```
ENGINE_API_KEY="someapikey"
ENGINE_ENDPOINT_URL="https://api.myapp.com"
```
and if no arguments were given, `apollo schema:publish` would just look for the env vars `ENGINE_API_KEY` and `ENGINE_ENDPOINT_URL`

**Comment by meatherly** [comment]
@jhalborg do you have a config file or are you just trying to use the it without? 
You could make a `apollo.config.js` file then require `dotenv` package and assign the environment variables that way.

**Comment by jhalborg** [comment]
Sure, that's a good idea, but it would be easier/cleaner, at least in my opinion, to be able to just pass in the .env file directly as an argument :)

**Comment by meatherly** [comment]
@jhalborg looks like it was added recently #815

**Comment by JakeDawkins** [comment]
Supporting completely custom env files could be tricky, since it would require another config option in VS Code. Since this issue itself is at least partially resolved, I'll close this issue for now. For a little more discussion and a workaround if existing solutions don't work for you, check out #1058
