### ISSUE TITLE
Update graphql to v14

### ISSUE THREAD

**Issue by trevor-scheer** [apollographql/apollo-tooling#626]
This issue is to upgrade packages dependent on graphql-js to v14.

v14 offers some handy utility functions for validating types of nodes.
They'll be useful here: #625

**Comment by justinanastos** [comment]
In addition, [`graphql@^0.13.2` is a dependency](https://github.com/apollographql/apollo-cli/blob/master/packages/apollo/package.json#L65). If the consumer has another version of `graphql` installed, such as `0.14.x`, then when the cli parses a `schema.json` file, it will use `0.14.x` and `instanceof` checks will fail because there's multiple versions of graphql. 

I suggest making `graphql` a `peerDependency` and setting the version to `>^0.13.2 || ^0.14.0`.

**Comment by justinanastos** [comment]
☝️ This will require updating the tests to run on both versions, which seems like something we should do anyway.

**Comment by daggerjames** [comment]
#624

**Comment by stevenpetryk** [comment]
#648 as well. These just keep on rolling in, and for some reason people cannot find the original issue for it either.

**Comment by stevenpetryk** [comment]
@trevor-scheer I think this also encompasses #630.
