### ISSUE TITLE
Schema Check fails w/ Error Code 2 - but only changes are type NOTICE

### ISSUE THREAD

**Issue by rockrep** [apollographql/apollo-tooling#695]
package.json
----
    "apollo": "2.0.15",
    "apollo-engine": "1.1.2",
    "apollo-link-context": "1.0.9",
    "apollo-link-http": "1.5.5",
    "apollo-server-cache-memcached": "0.2.0",
    "apollo-server-caching": "0.2.0",
    "apollo-server-express": "2.2.1",

```yarn apollo schema:check --key=$KEY --endpoint=http://localhost:7070/graphql
yarn run v1.9.4
.../node_modules/.bin/apollo schema:check --key=$KEY --endpoint=http://localhost:7070/graphql
 ✔ Loading Apollo Project
 ✔ Checking service for changes


Change  Code         Description
──────  ───────────  ───────────────────────────────────────
NOTICE  ARG_ADDED    `Channel.fiveUp` arg `region` was added
NOTICE  FIELD_ADDED  `MapMarker.markerName` was added
NOTICE  TYPE_ADDED   `CacheControlScope` added


error Command failed with exit code 2.
```

**Comment by jbaxleyiii** [comment]
@rockrep thanks for reporting this! I believe it should be fixed with https://github.com/apollographql/apollo-tooling/pull/691 (which is out on npm now as latest!) Can you try that out?

I'm really curious at where the `2` exit code is coming from though. @trevor-scheer was this the same issue you were seeing?
