### ISSUE TITLE
What replaced codegen:generate --schema=...

### ISSUE THREAD

**Issue by deltaskelta** [apollographql/apollo-tooling#696]
/label v2

I used to generate code with a local schema file something like this

```
apollo codegen:generate --schema=... --queries=... ./outputDir
```

but in v2 this seems to be removed. :( Is there anything that has replaced it?

**Comment by jbaxleyiii** [comment]
@deltaskelta you should be able to pass `--localSchemaFile=schema.json` or in your apollo.config.js

```
module.exports = {
  client: {
    localSchemaFile: "./schema.json"
  }
}
```

I *think* the `--localSchemaFile` flag isn't working yet but @trevor-scheer and @JakeDawkins should have that fixed this week!

**Comment by deltaskelta** [comment]
Ok thanks for the quick response, will there be a similar replacement for `--clientSchema` as well?

**Comment by disintegrator** [comment]
I've been also trying to track down what happened to `--clientSchema`. So far my initial walk through the codebase was fruitless. Can anyone let us know what replaced that option?

**Comment by martijnwalraven** [comment]
@deltaskelta @disintegrator The client schema is automatically generated if the included files have type definitions or extensions in them. I realize `--queries` is a bit of a misnomer for this, which is why this is specified as `includes` and `excludes` in the config. 

One of the great benefits of this is that it gives you a really great development experience when using the VS Code extension, where the client schema and queries can be edited hand in hand and will be validated together on the fly.

**Comment by deltaskelta** [comment]
Seems to be fixed now. Thanks!
