### ISSUE TITLE
/* GraphQL */ template strings not syntax highlighted

### ISSUE THREAD

**Issue by jaydenseric** [apollographql/apollo-tooling#724]
The VSCode "Apollo GraphQL" extension doesn't syntax highlight `/* GraphQL */` tagged template literal strings, like all other extensions do.

**Comment by lirbank** [comment]
A workaround is to set up a dummy `gql` tagged template that does nothing (but helps the tooling). I use it to get prettier to work with Typescript (https://github.com/prettier/prettier/issues/4679) 

```
const gql = String.raw;

const query = gql`
  query Viewer {
    viewer {
        id
    }
  }
`;
```

**Comment by jaydenseric** [comment]
@lirbank take a look at [`fake-tag`](https://github.com/jaydenseric/fake-tag), there are [issues with using `String.raw`](https://github.com/jaydenseric/fake-tag#why-not-stringraw).

These days I avoid tools that complicate projects/bundles; for now I'll stick to [Prisma's GraphQL extension](https://marketplace.visualstudio.com/items?itemName=Prisma.vscode-graphql) which respects `/* GraphQL */`.

**Comment by lirbank** [comment]
Oh, great! Thanks! @jaydenseric

**Comment by martijnwalraven** [comment]
I had never seen the use of `/* GraphQL */` comments instead of tagged template literals to mark GraphQL. Out of curiosity, what is the reason for wanting to avoid `gql` here? 

There are features we're looking to build on top of this, like automatically including referenced fragment definitions and generating query types, so I don't think we want to change our recommendation to use `gql`, but interested to hear what the downsides are for you.

**Comment by jaydenseric** [comment]
For starters, typeDef strings: https://github.com/jaydenseric/apollo-upload-examples/blob/1adea5abf6348020aa70299f09a42eaf91e9278f/api/types.mjs#L1

Some GraphQL clients don't use `gql` at all: https://github.com/jaydenseric/graphql-react-examples/blob/348308de581a2ddda76b8e0d7159202f90743b5f/components/pokemon.js#L16

It's not a niche thing, even Prettier recognises and formats `/* GraphQL */` template strings.

**Comment by jaydenseric** [comment]
> what is the reason for wanting to avoid `gql`

Smaller client bundles!

**Comment by martijnwalraven** [comment]
One thing to keep in mind is that the Apollo VS Code extension and other tools in this repo are meant to be opinionated and don't claim to support all use cases. We don't recommend the use of `typeDef` strings (these should be ASTs, we want to avoid string manipulation), and we're focused on Apollo Client. Given these constraints, I don't see a good reason to support `/* GraphQL */` to be honest.

**Comment by lirbank** [comment]
Our use case is that we use `graphql` (https://www.npmjs.com/package/graphql) for testing the server, so we don't need to fire up a server and a client for integration tests of the API/resolvers.

`graphql` only takes a `string` or a `Source` as the argument for the query. Since the API tests are in the same repo as the server, it makes sense if the vscode plugin can handle the GraphQL queries.

For now, we solved it with a fake `gql` template literal (which I anyway need for prettier to handle inline queries, as we're using TypeScript (see note above)).

@martijnwalraven I totally get that you don't want to support every single use case out there, but perhaps this is close enough a common setup (using `graphql` as a client to test Apollo servers)?

This is not a super important requirement for me though, since there is a workaround that works well, and it may be that we need to run the tests with apollo-client eventually to be able to test error handling properly. Just sharing my thoughts and our current use case.

**Comment by hwillson** [comment]
Thanks very much for the suggestion. At this time, adding `/* GraphQL */` support isn't part of our short to medium term project plans. Closing for now - thanks again!
