### ISSUE TITLE
[VSCode] Extension was unpublished

### ISSUE THREAD

**Issue by patrys** [apollographql/apollo-tooling#742]
The extension was pulled from the marketplace, it was forcefully uninstalled from our machines, the extension list marks it as "Malicious" and the details say:

>This extension was reported to be problematic.

**Comment by jbaxleyiii** [comment]
@patrys @audiBookning yep! Turns out that `vscode` itself (the package we use to build the extension) depended on the bad package. They have updated the package and so have we, and are now waiting on them to put the updated build back on the marketplace! Sorry for the inconvenience here! It should be resolved today!

**Comment by audiBookning** [comment]
Good news.
At this moment the extension seem to be all OK in VS Code.

**Comment by cirosantilli** [comment]
Did updating the dependencies automatically fix the issue? Or did you have to contact someone? I'm getting the same issue on my extension :-(
