### ISSUE TITLE
Error generating schema while using @client directives

### ISSUE THREAD

**Issue by SanchiSinghal** [apollographql/apollo-tooling#885]
Hi, Fail to generate the schema types when I'm using @client directive while using a query component and generating query using gql tag.

Getting the following error ::
.../queries/graphql/TransactionFee/Queries.ts: Cannot query field "abc" on type "Query".
.../queries/graphql/TransactionFee/Queries.ts: Cannot query field "xyz" on type "Query".
{ ToolError: Validation of GraphQL query document failed
at Object.validateQueryDocument (/home/projectname/.nvm/versions/node/v10.13.0/lib/node_modules/apollo/node_modules/apollo-language-server/lib/errors/validation.js:32:19)
at Object.generate [as default] (/home/projectname/.nvm/versions/node/v10.13.0/lib/node_modules/apollo/lib/generate.js:19:18)
at write (/home/projectname/.nvm/versions/node/v10.13.0/lib/node_modules/apollo/lib/commands/client/codegen.js:64:54)
at Task.task (/home/projectname/.nvm/versions/node/v10.13.0/lib/node_modules/apollo/lib/commands/client/codegen.js:83:46) name: 'ToolError' }
✔ Loading Apollo Project
✖ Generating query files with 'typescript' target
→ Validation of GraphQL query document failed

Here, abc and xyz are the local variables created using @client directive.

**Comment by JAFong** [comment]
I am getting a similar error
```
  ✔ Loading Apollo Project
  ✖ Generating query files with 'typescript' target
    → Validation of GraphQL query document failed
.../src/navigation/containers/MobileNavigation.tsx: Cannot query field "navigation" on type "Query".
.../src/product/containers/ProductConditionTabs.tsx: Cannot query field "productPage" on type "Query". Did you mean "product"?
.../src/product/containers/ProductQuestions.tsx: Cannot query field "productPage" on type "Query". Did you mean "product"?
.../src/product/containers/SizeSelector.tsx: Cannot query field "productPage" on type "Query". Did you mean "product"?
.../src/product/containers/UsedPairSelector.tsx: Cannot query field "productPage" on type "Query". Did you mean "product"?
.../src/shared/apollo/resolvers.ts: Cannot query field "navigation" on type "Query".
```

Both navigation and productPage are local variables using the *@client* directive.  I am using `apollo service:download -c apollo.config.server.j`  with the following config:

```
module.exports = {
  service: {
    endpoint: {
      url: 'http://localhost:3000/graphql',
    },
  },
}
```

Server side schema:
```
//server/schema.ts
import { makeExecutableSchema } from 'graphql-tools'
import Product, { resolver as ProductResolver } from './schemas/product'
import Availability, { resolver as AvailabilityResolver } from './schemas/availability'

const Query = `
  type Query {
    product: Product
    availability: Availability
  }
`

const SchemaDefinition = `
  schema {
    query: Query
  }
`

const rootResolvers = {
  Query: {
    product: ProductResolver,
    availability: AvailabilityResolver,
  },
}

export default makeExecutableSchema({
  typeDefs: [SchemaDefinition, Query, Product, Availability],
  resolvers: [rootResolvers],
})
```

Client Side schema
```
//src/schema.ts
const schemas = `
  type ProductPage {
    selectedSize: Float
  }

  type Navigation {
    isSearchOpen: Boolean
    isMenuOpen: Boolean
  }

  type Mutation {
    toggleIsSearchOpen
    toggleIsMenuOpen
  }

  type Query {
    productPage: ProductPage
    navigation: Navigation
  }
`

export default schemas
```

**Comment by JAFong** [comment]
Turns out my Client Side schema was invalid.

```
extend type Mutation {
    toggleIsSearchOpen: Boolean
    toggleIsMenuOpen: Boolean
  }
```

Is the code that was corrected

**Comment by justinanastos** [comment]
@SanchiSinghal I ran into a similar issue when I didn't wrap my `typeDefs` with `gql`:

```js
// This will not get picked up by codegen because it's missing `gql`
const typeDefs = ` ... `

// This will get picked up by codegen
const typeDefs = gql` ... `
```

**Comment by mattwexa** [comment]
Hi, I cannot seem to find a way to get types generated for my client schema. I've tried to define typeDefs in a .js file, to define types in a .graphql file, nothing seems to work. Do you have a working example somewhere with a `@client` directive and the associated schema that apollo client:codegen can work with? Thanks!

**Comment by JakeDawkins** [comment]
Hi @mattwexa! Our [fullstack tutorial](https://github.com/apollographql/fullstack-tutorial/tree/master/final/client) should work perfectly with codegen (although we don't do that in the tutorial itself).

- [the apollo.config.js](https://github.com/apollographql/fullstack-tutorial/blob/master/final/client/apollo.config.js)
- [client typedefs](https://github.com/apollographql/fullstack-tutorial/blob/master/final/client/src/resolvers.js)
- [client query](https://github.com/apollographql/fullstack-tutorial/blob/master/final/client/src/containers/action-button.js#L11)

Things to check for: 
- Make sure your `client.includes` glob isn't using a relative glob (i.e. use `src/**/*.ts` instead of `./src/**/*.ts`). these are broken right now until the next release

**Comment by JakeDawkins** [comment]
@SanchiSinghal Is this still an issue? Can you check your includes like I mentioned in the above comment if so, and provide any additional info about your config/file structure?

**Comment by mattwexa** [comment]
Hi @JakeDawkins! Thanks for the links to the client typedefs and query! I was able to make it work, no need for a `apollo.config.js` or `--includes` flag, the default of looking up files in `src` works fine.

I think that my issue was mispelling `extend` as `extends` :D The additional 's' seems to cause my schema to be ignored (I had tried both in a .graphql file and in a .js with gql tag), while there is no error in the output that indicates a syntax error. The only error I got was "Validation of GraphQL query document failed" because of the unknown client field. Should I open an issue for that?

**Comment by JakeDawkins** [comment]
Ohh interesting! That's a good point @mattwexa! Sure, if you'd like to open an issue for discussion around better error handling for schema validation errors that'd be great! 

I'm glad you got it fixed 😁 

I'll also close this issue since I _think_ it's been resolved, but I can open it back up if anyone objects :)
