### ISSUE TITLE
codegen with fragments in other js files...

### ISSUE THREAD

**Issue by deltaskelta** [apollographql/apollo-tooling#923]
Is it possible to get fragments from other js files without depending on string interpolation to add the fragments?

I am using gatsbyjs which uses its own graphql tag function that doesn't support interpolation. 

fragmentFile.js
```javascript
export const Frag = graphql`
  fragment Farg on Type {
    foo
  }
`
```

queryFile.ts
```typescript
export const query = graphql`
  query MyQuery {
    type {
      ...MyFrag
    }
  }
`;
```

as far as I can tell, in order to get fragments one should use string interpolation to include the fragment variable as a second arg to the query like this

queryFile.ts
```typescript
import { MyFrag } from './myFrag.js';

export const query = graphql`
  query MyQuery {
    type {
      ...MyFrag
    }
  }
  ${MyFrag}
`;
```

but would it be possible to include both files using the `--includes` flag and have apollo match things up for me?

**Comment by vadistic** [comment]
Hello @deltaskelta 

I think it's already works this way. I'm sure old `apollo 1.9.2` for `graphql 0.13.2` version works this way. 

When I'm using gatsby (which does not support graphql 14 yet and thus why I'm using old apollo cli version) - I'm not importing fragments because gatsby finds all exported graphql constanst and compile it (using relay I think). Apollo codegen works fine with it.

Here's example: https://github.com/vadistic/generic-portfolio-starter/tree/example , see e.g. this query: https://github.com/vadistic/generic-portfolio-starter/blob/example/src/templates/work.tsx

For more usual setup using `apollo-client` and `gql-tag` not importing fragments would cause you a problem, because query without fragments is not a valid valid query. `gql-tag` does not validate `DocumentNode` for missing types, but the moment you would pass it to the client, you will get error console log `Missing fragment MyFrag on type MyQuery ....`

You can also use the webpack loader from `gql-tag/loader` to use `#import "../fragments.graphql"` syntax if string interpolation imports are too bothersome (but I actually prefer them because of editor support).

**Comment by deltaskelta** [comment]
what version of apollo are you running? it is not listed in your package.json

I tried this command with `apollo/2.3.1 darwin-x64 node-v11.8.0` and it failed. I don't see anything majorly different from yours. This command works if I don't use the fragment in my graphql...

```
    "get-schema": "apollo service:download --endpoint http://localhost:8001/___graphql ./gatsby-schema.json",
    "gatsby-gen": "apollo client:codegen --addTypename --outputFlat --tagName=graphql --target=typescript --localSchemaFile=./gatsby-schema.json --includes=./src/**/*.tsx ./src/gatsby-queries.d.ts",
    "gen": "yarn get-schema && yarn gatsby-gen",
```

the part of the query that fails is a gatsby image fragment

```
        images {
          publicURL
          childImageSharp {
            fluid {
              ...GatsbyImageSharpFluid_tracedSVG
            }
          }
        }
```

**Comment by vadistic** [comment]
My setup is:
`apollo/1.9.2 linux-arch node-v11.8.0`

I wrote `apollo 1.9.2` and it's there in package: https://github.com/vadistic/generic-portfolio-starter/blob/example/package.json#L47

I'm using older version because I prefer not using global modules and gatsby does not support yet graphql 14+. You may need to specify resolutions (it's yarn only!) in your package.json (and reinstall node_modules after doing it)

https://github.com/vadistic/generic-portfolio-starter/blob/example/package.json#L57-L60

And try deleting your apollo config, because it's sometimes cause undeterministic issues :)

**Comment by vadistic** [comment]
I have one more idea:
You need to make sure you have those fragments declared and exported somewhere like I did:

https://github.com/vadistic/generic-portfolio-starter/blob/example/src/fragments.ts

**Comment by deltaskelta** [comment]
Sorry IDK how I missed the version two times, it was pretty late. I see what happened now. The fragments are already in the .cache folder of gatsby so I was able to just change my glob like below rather than redeclaring them under a different name...

```
    "gatsby-gen": "apollo client:codegen --addTypename --outputFlat --tagName=graphql --target=typescript --localSchemaFile=./gatsby-schema.json  --includes='./{src,.cache}/**/*.{ts,tsx,js,jsx}' ./src/gatsby-queries.d.ts",
```

**Comment by dminkovsky** [comment]
Anyone know if this is supported in 2.3.x? Not getting this to work.

**Comment by CollinCashio** [comment]
> Anyone know if this is supported in 2.3.x? Not getting this to work.

I am not getting this to work either in 2.3.
