### ISSUE TITLE
`client:push` operation is re-ordering document definitions

### ISSUE THREAD

**Issue by justinanastos** [apollographql/apollo-tooling#986]
The problem lies here:

https://github.com/apollographql/apollo-tooling/blob/b6dde38b0b00d7b693cf3d845b6af67bbeb43289/packages/apollo-language-server/src/project/client.ts#L323-L333

The order of the definitions is changed, and then the result is hashed. When we use `apollo-server-plugin-operation-registry ` and turn on `forbidUnregisteredOperations` (https://www.apollographql.com/docs/platform/operation-registry.html#Installation-steps), the operation is received in it's original order, hashed, and then compared. If the order does not match, the operation will be rejected.

Side note: It might be possible that we're relying on `apollo-server`'s `sortAST` to correctly order the AST. Looking at that function, unless I'm reading it incorrectly, it does _not_ re-order operations, but instead normalizes content inside them.

https://github.com/apollographql/apollo-server/blob/master/packages/apollo-graphql/src/transforms.ts#L97-L151

Two possible solutions:

1. Find a way to maintain the original order of the definitions in the original document. This could easily be tested, even though it might be harder to implement. 

    The operation registry has the luxury the browser interpolating the gql at runtime.

2. Change `sortAST` to sort the `definition`s in a `document`. I don't know what the ramifications of this would be.

**Comment by trevor-scheer** [comment]
See https://github.com/apollographql/apollo-server/pull/2282 for initial work and tracking progress. Once this PR lands, transitive dependencies will need to be updated to use the new `apollo-graphql` package for normalizing operation signatures.

**Comment by abernix** [comment]
This should be fixed via #1027.  Anyone who is experiencing this problem (which appears to be a fair number, based on 👍 s!) should:

* Re-register all of their operations with a new version of the `apollo` CLI which @trevor-scheer and I published under the `register` tag.  Users who do not have `apollo` installed into their `devDependencies` of their project's `package.json` can use:

      npx apollo@register client:push

  While this is currently a "3.x alpha" of the `apollo` CLI, it is only done that way for semantic versioning reasons: to avoid users inadvertently updating to it.  It is otherwise functionally identical to 2.x releases of Apollo and we will back-port this functionality to `apollo@2` if and when possible.  In order to unblock users who are _currently_ experiencing the problem with fragments though, we're offering this immediate upgrade path.
* **After re-registering all operations using `client:push` on the new version** update their `apollo-server-plugin-operation-registry` to the newer version, currently published on the `next` tag: `npm install apollo-server-plugin-operation-registry@next`.

We encourage anyone who is [an Apollo Engine plan which includes the operation registry](https://www.apollographql.com/plans/) can reach out on Intercom support for help in this upgrade process and someone will be happy to assist.

**Comment by abernix** [comment]
cc @ctbradley
