### ISSUE TITLE
schema publish error: read ECONNRESET

### ISSUE THREAD

**Issue by yangchongduo** [apollographql/apollo-tooling#993]
I have the same problem when i start fullstack-tutorial and push service
https://user-images.githubusercontent.com/19523872/50539098-80d5eb80-0bb5-11e9-8da2-449021f3fdc3.png
what should i do

schema publish error: read ECONNRESET

**Comment by JakeDawkins** [comment]
Hi @yangchongduo, is this still happening? I haven't seen this happen to anyone else. It could be an issue with any VPNs or a network issue.

**Comment by yangchongduo** [comment]
@JakeDawkins  I have already handled it through travis, but I feel that you should have some plans, not to tell the reason, so that it can be easily promoted.

**Comment by yangchongduo** [comment]
I feel that it is too long for you to deal with the problem. It’s been 18 days.

**Comment by JakeDawkins** [comment]
@yangchongduo Yeah, sorry! We've been trying to figure out how to best handle issues in this project since they're so broad, and we've been slow to respond for sure. 

In the future, if you're running into problems and have questions you need help with more quickly, our [spectrum chat community](https://spectrum.chat/apollo) may be able to help :) 

Since this is fine now, I'll close this issue
